name: 02-node-challenge-rocketseat

services:
  app_db:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=daily_diet

  # test_db:
  #   image: bitnami/postgresql:13.16.0
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_DB=daily_diet_test